apiVersion: v1
kind: Service
metadata:
  labels:
    app: cafestatic
  name: cafestatic
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085
      protocol: TCP
  selector:
    app: cafestatic
